// R6.10 — the three things this system will not do, enforced rather than promised.
//
// These are not accidents a reasonable build stumbles into. They are the
// standard growth-hack playbook for cold email, every one of them is a
// deliberate choice someone makes, and every one of them is the kind of thing
// a future "let's improve deliverability" change would reach for first. So
// each is written down with its reason and given a check that fails.
//
//  1. NO FABRICATED ENGAGEMENT.
//     Opens, clicks and replies may only be counted when a provider event says
//     they happened. Not inferred, not simulated, and never generated by us to
//     warm a mailbox. Fake engagement is fraud against the provider's
//     reputation system and it corrupts the only numbers that tell the owner
//     whether any of this works.
//
//  2. NO DOMAIN ROTATION.
//     One sending domain, named. Rotating through lookalike domains exists to
//     outrun a reputation you have earned — it is the mechanism that lets bad
//     sending continue instead of being corrected. A separate domain from the
//     client-report domain limits blast radius (R6.3) and that is ALL it does;
//     a second prospecting domain is rotation, whatever it is called.
//
//  3. NO FILTER EVASION.
//     No zero-width characters, no homoglyph substitution, no hidden text, no
//     image-only bodies hiding the message from text filters, no redirect
//     chains disguising a destination. A spam filter is a recipient's agent.
//     Evading it is deciding on their behalf that they want this.
//
// The checks run on OUR OWN outgoing copy. If the composer ever emits one of
// these it is a bug, and this is where it stops being shipped.

export const PROHIBITED = Object.freeze([
  {
    id: 'fabricated-engagement',
    rule: 'Opens, clicks and replies are counted only from provider events.',
    why: 'Inventing engagement defrauds the provider\'s reputation system and destroys the only numbers that say whether this works.',
  },
  {
    id: 'domain-rotation',
    rule: 'One prospecting domain, named in the settings. No pool, no rotation.',
    why: 'Rotation exists to outrun a reputation you earned, which lets bad sending continue instead of being corrected.',
  },
  {
    id: 'filter-evasion',
    rule: 'No hidden text, homoglyphs, zero-width characters, image-only bodies or redirect chains.',
    why: 'A spam filter acts for the recipient. Evading it decides on their behalf that they want this.',
  },
]);

// ---------------------------------------------------------------------------
// 3. Filter evasion, detected in our own copy
// ---------------------------------------------------------------------------

/** Characters with no visual width, used to break up words filters look for. */
const ZERO_WIDTH = /[​-‍⁠﻿­]/g;

/**
 * Cyrillic and Greek letters that look like Latin ones. Writing "Ì€ree" with a
 * Cyrillic Ðµ is the classic way to say a word a filter watches for without
 * the filter seeing it.
 */
const CONFUSABLES = {
  'а': 'a', 'е': 'e', 'о': 'o', 'р': 'p', 'с': 'c',
  'х': 'x', 'у': 'y', 'і': 'i', 'ј': 'j', 'һ': 'h',
  'α': 'a', 'ο': 'o', 'ρ': 'p', 'ν': 'v', 'ѕ': 's',
};

/** Words chopped with punctuation to slip past a matcher: f-r-e-e, c.l.i.c.k */
const CHOPPED = /\b(?:[a-z][^a-z0-9\s]){3,}[a-z]\b/i;

export function findEvasion(text = '', { html = '' } = {}) {
  const findings = [];
  const s = String(text || '');
  const h = String(html || '');

  const zw = s.match(ZERO_WIDTH);
  if (zw) {
    findings.push({
      kind: 'zero-width',
      count: zw.length,
      text: `${zw.length} invisible character(s) in the body. These exist only to break up words a filter looks for.`,
    });
  }

  const confusables = [...s].filter((ch) => CONFUSABLES[ch]);
  if (confusables.length) {
    findings.push({
      kind: 'homoglyph',
      count: confusables.length,
      text: `${confusables.length} letter(s) from another alphabet that look Latin (${[...new Set(confusables)].join(' ')}). This is how a word is written so a filter cannot read it.`,
    });
  }

  if (CHOPPED.test(s)) {
    findings.push({ kind: 'chopped-word', text: 'A word is broken up with punctuation (like f.r.e.e), which only makes sense to defeat a matcher.' });
  }

  if (h) {
    if (/display\s*:\s*none|visibility\s*:\s*hidden|font-size\s*:\s*0|color\s*:\s*#?f{3,6}\b[^;]*background[^;]*#?f{3,6}/i.test(h)) {
      findings.push({ kind: 'hidden-text', text: 'The HTML hides text from the reader while leaving it for the filter to read.' });
    }
    const textLen = h.replace(/<[^>]+>/g, '').replace(/\s+/g, '').length;
    const imgs = (h.match(/<img\b/gi) || []).length;
    if (imgs > 0 && textLen < 40) {
      findings.push({ kind: 'image-only', text: 'The message is essentially an image with no readable text, which hides the content from text filters and from anyone who blocks images.' });
    }
  }

  return findings;
}

/** A destination that hides behind several hops is a destination being hidden. */
export function findRedirectChains(text = '', { allowedHosts = [] } = {}) {
  const findings = [];
  const urls = String(text || '').match(/https?:\/\/[^\s<>")]+/gi) || [];
  for (const u of urls) {
    let parsed;
    try { parsed = new URL(u); } catch { continue; }
    // a URL carrying another URL is a redirect, whatever the host is called
    const inner = /https?%3A%2F%2F|https?:\/\/[^\s]*https?:\/\//i.test(u);
    const shortener = /^(bit\.ly|tinyurl\.com|t\.co|goo\.gl|ow\.ly|buff\.ly|rebrand\.ly|cutt\.ly|is\.gd)$/i.test(parsed.hostname);
    if (inner) findings.push({ kind: 'nested-redirect', url: u, text: `${parsed.hostname} carries another URL inside it, which disguises where the link actually goes.` });
    else if (shortener) findings.push({ kind: 'shortener', url: u, text: `${parsed.hostname} is a link shortener, so neither the recipient nor a filter can see the destination.` });
    else if (allowedHosts.length && !allowedHosts.some((hst) => parsed.hostname === hst || parsed.hostname.endsWith(`.${hst}`))) {
      findings.push({ kind: 'unexpected-host', url: u, text: `${parsed.hostname} is not one of the hosts this system sends links to.` });
    }
  }
  return findings;
}

// ---------------------------------------------------------------------------
// 2. Domain rotation
// ---------------------------------------------------------------------------

/**
 * One prospecting domain. Several configured means rotation, and rotation is
 * refused — the point of the separate domain is blast radius, not evasion.
 */
export function checkSendingDomains(env = process.env) {
  const raw = String(env.OUTREACH_FROM_DOMAIN || '').trim();
  const domains = raw.split(/[,\s;]+/).filter(Boolean);
  const problems = [];
  if (domains.length > 1) {
    problems.push({
      kind: 'domain-rotation',
      text: `${domains.length} prospecting domains are configured (${domains.join(', ')}). This system sends from one. Rotating domains exists to outrun a reputation you earned, and it is refused.`,
    });
  }
  // a numbered family — mail1, mail2 — is a rotation pool with extra steps
  const pool = Object.keys(env).filter((k) => /^OUTREACH_FROM_DOMAIN_?\d+$/i.test(k));
  if (pool.length) {
    problems.push({ kind: 'domain-pool', text: `A numbered domain pool is configured (${pool.join(', ')}). Only OUTREACH_FROM_DOMAIN is used; a pool is rotation.` });
  }
  return { domain: domains[0] || null, count: domains.length, problems, ok: problems.length === 0 };
}

// ---------------------------------------------------------------------------
// 1. Fabricated engagement
// ---------------------------------------------------------------------------

export const ENGAGEMENT_SOURCE = Object.freeze({
  PROVIDER_EVENT: 'provider-event',
  OWNER_RECORDED: 'owner-recorded',
});

/**
 * The only two ways an engagement fact may enter the system.
 *
 * Anything else — an inference, a default, a simulation, a warm-up routine —
 * is refused here rather than being allowed in and labelled carefully later.
 * A number that got in is a number that eventually gets reported.
 */
export function acceptEngagement({ kind, source, at = Date.now(), evidence = null }) {
  const allowed = Object.values(ENGAGEMENT_SOURCE);
  if (!allowed.includes(source)) {
    return {
      ok: false,
      reason: `engagement may only come from ${allowed.join(' or ')}; "${source || 'nothing'}" is not evidence that anyone did anything`,
    };
  }
  if (source === ENGAGEMENT_SOURCE.PROVIDER_EVENT && !evidence) {
    return { ok: false, reason: 'a provider event must carry the event it came from' };
  }
  return { ok: true, kind, source, at, evidence };
}

/**
 * The whole gate, run before a message goes out.
 * Returns `{ ok, findings }` — `ok: false` means do not send this.
 */
export function checkOutgoing({ text = '', html = '', env = process.env, allowedHosts = [] } = {}) {
  const findings = [
    ...findEvasion(text, { html }),
    ...findRedirectChains(text, { allowedHosts }),
    ...checkSendingDomains(env).problems,
  ];
  return { ok: findings.length === 0, findings };
}
